## The functions makeCacheMatrix and cacheSolve when combined generate a square invertible
## matrix, calculate the inverse, and retrieves/stores it in the the cache object.

##This function generates the matrix object and can cache its inverse

makeCacheMatrix <- function(x = matrix()) {  
        
        cache <- NULL  ##working environment to store matrix inversions, initialized to NULL
        
        set <- function(y) {  ## set the matrix in the cache environment
                x <<- y
                cache <<- NULL
        }
        
        get <- function() x                            ## get the matrix
        setmat <- function(inverse) cache <<- inverse  ##invert matrix and store in cache
        getinv <- function() cache                     ##get the inverted matrix from cache
        
        list( set=set, get=get, setmat=setmat, getinv=getinv)  ##return functions to working environment

}

##This function calculates the inverse of the matrix generated by makeCacheMatrix.  If the inverse
##has been calculated previously it will retrieve it from the cache.  

cacheSolve <- function(x,...) {
        
        cache <- x$getinv()                             ##get the matrix inverse if it exists
        if(!is.null(cache)) {                           ##check to see if inverse is in cache
                print("getting cached data")
                return(cache)
        }
        cache <- solve(x$get())                         ##calculate the new matrix' inverse
        x$setmat(cache)                                 ##set inverted matrix in cache
        return(cache)
}
